# Generated by Django 3.2.9 on 2021-12-22 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shift_maker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Block_name', models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3'), ('a4', 'A4'), ('b12', 'B12'), ('b3', 'B3'), ('b4', 'B4'), ('c12', 'C12'), ('c34', 'C34'), ('all', 'All')], max_length=3)),
                ('room_number', models.IntegerField()),
                ('account_name', models.CharField(max_length=40, unique=True, verbose_name='アカウント名')),
                ('workload_sum', models.IntegerField(default=0, verbose_name='過去の仕事量')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', shift_maker.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentname', models.CharField(max_length=25)),
                ('workload', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workname', models.CharField(blank=True, max_length=30, null=True)),
                ('day', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('days_from_start', models.PositiveIntegerField(blank=True)),
                ('required_number', models.PositiveIntegerField()),
                ('is_decided', models.BooleanField(default=False)),
                ('content', models.ForeignKey(default='無し', on_delete=django.db.models.deletion.SET_DEFAULT, to='shift_maker.workcontent')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_template_name', models.CharField(max_length=40, verbose_name='テンプレート名')),
                ('slot_templates', models.ManyToManyField(to='shift_maker.Slot')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=40, verbose_name='シフト名')),
                ('first_day', models.DateField()),
                ('deadline', models.DateField()),
                ('target', models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3'), ('a4', 'A4'), ('b12', 'B12'), ('b3', 'B3'), ('b4', 'B4'), ('c12', 'C12'), ('c34', 'C34'), ('all', 'All')], max_length=3)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ManyToManyField(to='shift_maker.Slot')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_work',
            field=models.ManyToManyField(blank=True, to='shift_maker.WorkContent', verbose_name='経験済みの仕事'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigning_slot',
            field=models.ManyToManyField(blank=True, to='shift_maker.Slot'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
