# Generated by Django 3.2.9 on 2021-12-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='slot',
            field=models.ManyToManyField(blank=True, to='shift_maker.Slot'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='slot_templates',
            field=models.ManyToManyField(blank=True, null=True, to='shift_maker.Slot'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Block_name',
            field=models.CharField(blank=True, choices=[('a1', 'A1'), ('a2', 'A2'), ('a3', 'A3'), ('a4', 'A4'), ('b12', 'B12'), ('b3', 'B3'), ('b4', 'B4'), ('c12', 'C12'), ('c34', 'C34'), ('all', 'All')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='room_number',
            field=models.IntegerField(default=100),
        ),
    ]
